### ISSUE TITLE
Home Assistant - Missing module PyXantech

### ISSUE THREAD

**Issue by DamianFlynn** [rsnodgrass/hass-xantech#1]
Hi,

Thank you - I have 2 MRC88's which have been unused since moving to Home Assistant, so very excited to have the opportunity to get these back online. 

I have created a NEW installation of Home Assistant (2021.01), Installed HACS, and added your integration repository for `rsnodgrass/hass-xantech`  and then installed the integration to my instance.

In the configuration I have then added your sample, but swapped the port to use socket as suggested in the monoprice docs, as i am using a itach device (physical).

```
media_player:
  - platform: xantech
    type: xantech8
    #port: /dev/ttyUSB0
    port: socket://172.16.1.246:4999
    zones:
      11:
        name: "Main Bedroom"
      12:
        name: "Living Room"
      13:
        name: "Kitchen"
    sources:
      1:
        name: "Sonos"
      5:
        name: "FireTV"
```

However, I am getting an error that your `pyxantech` module is not installed, have I missed a step? I see the current version is 0.5.20 and the referenced version is 0.5.12; I did update the requirement, but the net result was the same, so rolled back.

Platform error media_player.xantech - No module named 'pyxantech'

```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:420
Integration: Hass.io (documentation, issues)
First occurred: January 11, 2021, 11:32:55 PM (2 occurrences)
Last logged: January 11, 2021, 11:41:03 PM
Platform error media_player.xantech - No module named 'pyxantech' 
```
